@basUrl = http://localhost:3333/nest-clean
@authToken ={{authenticate.response.body.access_token}}


# @name create_account
POST {{basUrl}}/accounts
Content-Type: application/json

{
  "name": "Diego",
  "email": "diego7@gmail.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{basUrl}}/sessions
Content-Type: application/json

{
  "email": "diego6@gmail.com.br",
  "password": "123456"
}


###

# @name create_question
POST {{basUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "nova pergunta 9",
  "content": "conteúdo"
}

###

# @name fetch_recent_questions
GET {{basUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
