services:
  app:
    container_name: nest-clean-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'postgresql://nest_clean:senha@shared-postgres:5432/nest_clean?schema=public'
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      PORT: 3333
    restart: unless-stopped
    networks:
      - web
      - database
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nest-clean.rule=PathPrefix(`/nest-clean`)'
      - 'traefik.http.routers.nest-clean.entrypoints=web'
      - 'traefik.http.services.nest-clean.loadbalancer.server.port=3333'
      - 'traefik.docker.network=web'

networks:
  web:
    external: true
  database:
    external: true
